testId: validation11
type: randomTemplate
url : https://jsonplaceholder.typicode.com/posts
duration: 4 #seconds
count: 10
request:
  method: POST
  randomFields:
    id:
      - prueba
      - prueba1
      - prueba2
      - prueba3
      - prueba4
    value:
      - value
      - value1
      - value2
      - value3
      - value4
    date:
      - Date #currently date
  headers:
    content-type: application/json
    #randomize in body
  body: >
          {
          "id": "{{id}}",
          "value": "{{value}}",
          "date": "{{date}}"
          }
---
testId: validation12
type: random
url : https://jsonplaceholder.typicode.com/posts
duration: 4 #seconds
count: 100
request:
  method: POST
  headers:
    content-type: application/json
  body: #randomize in body
    id:
      - prueba
      - prueba1
      - prueba2
      - prueba3
      - prueba4
    value:
      - value
      - value1
      - value2
      - value3
      - value4
    date:
      - Date #currently date
---
testId: validation14
type: interval
url: http://localhost:3000/test
request:
  method: POST
  headers:
    content-type: application/json
    heade1: val
  body:
    id: MyID
    value: XXX
tenants:
  - id: t1
    method: POST
    intervals: #count
      - 8
      - 5
    duration: 1
  - id: t2
    intervals:
      - 6
      - 4
    duration: 1
  - id: t3
    intervals:
      - 1
      - 8
    duration: 1
  - id: t4
    intervals:
      - 3
      - 3
    duration: 1
---
testId: validation13
type: long
url : https://twitter.com/
duration: 3 #seconds
count: 2
method: GET
---
testId: validation16
type: long
url : https://google.es
duration: 1 #seconds
count: 3
method: GET
